### ISSUE TITLE
Unity.Configuration is not built against latest dependencies

### ISSUE THREAD

**Issue by timg83** [unitycontainer/configuration#12]
The latest version of Unity.configuration available through Nuget is not built against the latest version of it's dependencies.

![afbeelding](https://user-images.githubusercontent.com/2979347/51907310-ae859e80-23c6-11e9-8845-aa6feb430e3b.png)

As a result you have to use assembly binding redirects in order to make use of the new Unity assembly versions. Is there a reason why the Unity.configuration lib is not built against the latest versions of it's dependencies?

**Comment by ENikS** [comment]
Libraries are rebuilt only when changed. 

Dependencies are referenced [using interval notation](https://github.com/unitycontainer/configuration/blob/master/package.props) so, when built, it should always pick the latest. Your problem is how you install these dependencies. [This article](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-2.8) should explain how it should be done properly.
